<a href="https://colab.research.google.com/github/leesujin1209/BlockChain/blob/main/8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##로지스틱 회귀





In [3]:
import numpy as np
import pandas as pd
fish = pd.read_csv('http://bit.ly/fish_csv_data')
print(pd.unique(fish['Species']))
print(fish)                                     # print(fish.head())

['Bream' 'Roach' 'Whitefish' 'Parkki' 'Perch' 'Pike' 'Smelt']
    Species  Weight  Length  Diagonal   Height   Width
0     Bream   242.0    25.4      30.0  11.5200  4.0200
1     Bream   290.0    26.3      31.2  12.4800  4.3056
2     Bream   340.0    26.5      31.1  12.3778  4.6961
3     Bream   363.0    29.0      33.5  12.7300  4.4555
4     Bream   430.0    29.0      34.0  12.4440  5.1340
..      ...     ...     ...       ...      ...     ...
154   Smelt    12.2    12.2      13.4   2.0904  1.3936
155   Smelt    13.4    12.4      13.5   2.4300  1.2690
156   Smelt    12.2    13.0      13.8   2.2770  1.2558
157   Smelt    19.7    14.3      15.2   2.8728  2.0672
158   Smelt    19.9    15.0      16.2   2.9322  1.8792

[159 rows x 6 columns]


In [8]:
import numpy as np
import pandas as pd

fish = pd.read_csv('http://bit.ly/fish_csv_data')
print(pd.unique(fish['Species']))
print(fish.head())

['Bream' 'Roach' 'Whitefish' 'Parkki' 'Perch' 'Pike' 'Smelt']
  Species  Weight  Length  Diagonal   Height   Width
0   Bream   242.0    25.4      30.0  11.5200  4.0200
1   Bream   290.0    26.3      31.2  12.4800  4.3056
2   Bream   340.0    26.5      31.1  12.3778  4.6961
3   Bream   363.0    29.0      33.5  12.7300  4.4555
4   Bream   430.0    29.0      34.0  12.4440  5.1340


In [11]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split


fish = pd.read_csv('http://bit.ly/fish_csv_data')
fish_input = fish[['Weight','Length','Diagonal','Height','Width']].to_numpy()
fish_target = fish['Species'].to_numpy()

train_input, test_input, train_target, test_target = train_test_split(fish_input, fish_target, random_state=42)

훈련 셋과 테스트 셋을 분리

In [12]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


fish = pd.read_csv('http://bit.ly/fish_csv_data')
fish_input = fish[['Weight','Length','Diagonal','Height','Width']].to_numpy()
fish_target = fish['Species'].to_numpy()

train_input, test_input, train_target, test_target = train_test_split(fish_input, fish_target, random_state=42)

ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

최근접 이웃 - 스케일링

In [19]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

fish = pd.read_csv('http://bit.ly/fish_csv_data')
fish_input = fish[['Weight','Length','Diagonal','Height','Width']].to_numpy()
fish_target = fish['Species'].to_numpy()

train_input, test_input, train_target, test_target = train_test_split(fish_input, fish_target, random_state=42)

ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

from sklearn.neighbors import KNeighborsClassifier
kn = KNeighborsClassifier(n_neighbors=3)        # n_neighbors=3, n_neighbors=10

kn.fit(train_scaled, train_target)
print(test_target[:5])                           # 실제 값
print(kn.predict(test_scaled[:5]))               # 예측 값
# print(kn.classes_)                             # 클래스 이름 출력, 알파벳순 배열
proba = kn.predict_proba(test_scaled[:5])        # 클래스별로 확률 확인

print(np.round(proba, decimals=4))               # 소수점 4자리수까지 반올림

['Perch' 'Smelt' 'Pike' 'Whitefish' 'Perch']
['Perch' 'Smelt' 'Pike' 'Perch' 'Perch']
[[0.     0.     1.     0.     0.     0.     0.    ]
 [0.     0.     0.     0.     0.     1.     0.    ]
 [0.     0.     0.     1.     0.     0.     0.    ]
 [0.     0.     0.6667 0.     0.3333 0.     0.    ]
 [0.     0.     0.6667 0.     0.3333 0.     0.    ]]


##로지스틱을 이용한 이진분류: 돔과 빙어

sigmoid(z),시그모이드 함수

z 값을 입력받아 0과 1 사이의 값으로 출력

0.5를 기준으로 작으면 음수 크면 양수

In [29]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split


fish = pd.read_csv('http://bit.ly/fish_csv_data')
fish_input = fish[['Weight','Length','Diagonal','Height','Width']].to_numpy()
fish_target = fish['Species'].to_numpy()

train_input, test_input, train_target, test_target = train_test_split(fish_input, fish_target, random_state=42)

ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

bream_smelt_indexes = (train_target == 'Bream') | (train_target == 'Smelt')    # 돔과 방어의 인덱스 추출       # 돔과 빙어의 인덱스 추출
train_bream_smelt = train_scaled[bream_smelt_indexes]
target_bream_smelt = train_target[bream_smelt_indexes]
# print(train_target)
# print(target_bream_smelt)

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(train_bream_smelt, target_bream_smelt)

print(lr.predict(train_bream_smelt[:5]))                          # 예측 값
print(lr.classes_)
print(np.round(lr.predict_proba(train_bream_smelt[:5]), decimals=3))

print(lr.coef_, lr.intercept_)                                    # 가중치 찍어보기
decisions = lr.decision_function(train_bream_smelt[:5])           # z 출력
print(decisions)
print(np.round(decisions, decimals=2))

from scipy.special import expit
print(expit(decisions))                                           # expit는 시그모이드 함수로 돔 0, 빙어 1에 대한 확률을 출력

['Bream' 'Smelt' 'Bream' 'Bream' 'Bream']
['Bream' 'Smelt']
[[0.998 0.002]
 [0.027 0.973]
 [0.995 0.005]
 [0.986 0.014]
 [0.998 0.002]]
[[-0.40451732 -0.57582787 -0.66248158 -1.01329614 -0.73123131]] [-2.16172774]
[-6.02991358  3.57043428 -5.26630496 -4.24382314 -6.06135688]
[-6.03  3.57 -5.27 -4.24 -6.06]
[0.00239993 0.97262675 0.00513614 0.01414953 0.00232581]


회귀라는 모델들은 어떤 값을 예측 하는 것임

분류하고 회귀 배움

분류는 이게 맞냐 이게 맞냐 하는 거 = 정확도 100개중에 몇 개 맞췄다

회귀문제는 키가 몇센치일때 몇킬로다 이런건 못 맞춰 정확도가 아니고 결정 계수

시그모이드 함수를 적용해가지고 돔이냐 빙어냐 확률을 내는 것